services:
  db:
    image: postgres
    container_name: senai-db
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./initial-dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: senai
    ports:
      - "5432:5432"
    networks:
      - senai-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: senai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - senai-network

volumes:
  db-data:
    name: senai-db
networks:
  senai-network:
    driver: bridge
